Updated srs
audio-engineer/aau-p1-article pull request #45
Opened 2023-11-21 11:53 UTC by MadsHeilmann

2023-11-22 10:33 UTC, Danar435 commented on src/problem-solution/srs.tex
> +In contrast, the ''Nice to haves'' include functions which are out of scope of this report, but would improve the
'' før nice/need to haves skal være ``

2023-11-22 14:10 UTC, Danar435 approved these changes

2023-11-24 18:01 UTC, TexWO approved these changes

2023-11-25 09:31 UTC, audio-engineer requested changes

2023-11-25 09:31 UTC, audio-engineer commented on src/problem-analysis/emissions.bib
> +
@MadsHeilmann Unnecessary empty line

2023-11-25 09:31 UTC, audio-engineer commented on src/problem-solution/srs.tex
> +% textidote: ignore end
@MadsHeilmann Why are you ignoring 5 lines? Have you tried ignoring one line only?
```suggestion
% textidote: ignore begin
In contrast, the ``nice to have's'' include functions which are out of scope of this report, but would improve the program if implemented.
% textidote: ignore end
```

2023-11-28 10:04 UTC, Danar435 requested changes

2023-11-28 10:04 UTC, Danar435 commented on src/problem-solution/srs.tex
> +In contrast, the ``nice to have's'' include functions which are out of scope of this report, but would improve the program if implemented.
Line repeated twice, why not delete line 11-13?

2023-11-28 11:51 UTC, Danar435 approved these changes

2023-12-02 13:25 UTC, MadsHeilmann commented on src/problem-solution/srs.tex
> +% textidote: ignore end
Yes - I have now made it cover fewer lines

2023-12-02 21:53 UTC, audio-engineer approved these changes

2023-12-02 22:04 UTC, audio-engineer commented
@MadsHeilmann I see that you have some merge conflicts. Do you need my help in resolving them or will you do it yourself?

2023-12-03 12:42 UTC, merged