Added price calculations
audio-engineer/aau-p1-article pull request #46
Opened 2023-11-24 16:21 UTC by Danar435

2023-11-24 18:01 UTC, TexWO approved these changes

2023-11-26 08:32 UTC, audio-engineer requested changes

2023-11-26 08:32 UTC, audio-engineer commented on src/main.tex
> -\usepackage[indent=20pt]{parskip}
why? just leave the indent. It looks much better

2023-11-26 08:32 UTC, audio-engineer commented on src/problem-solution/calculations.tex
> +\section{Calculating the attributes}
Can you add labels to all of these?

2023-11-26 08:32 UTC, audio-engineer commented on src/problem-solution/calculations.tex
> +    \frac{3750 - 2487}{2} + 663 = 1294 kr
You probably want to use a package to render the currency symbol. Or at least `\text`

2023-11-26 10:18 UTC, Danar435 commented on src/main.tex
> -\usepackage[indent=20pt]{parskip}
I personally think it looks better without indents, maybe something to discuss in the next meeting

2023-11-27 11:23 UTC, Danar435 commented on src/main.tex
> -\usepackage[indent=20pt]{parskip}
![image](https://github.com/audio-engineer/aau-p1-article/assets/60707126/fa1464c6-5bf4-4439-8ca0-f96d726e7226)
Without and with indent. Notice how the first paragraph is not indented. That's why I don't like the look of it - it's not consistent.

2023-11-27 14:30 UTC, audio-engineer commented on src/main.tex
> -\usepackage[indent=20pt]{parskip}
It doesn't have to be indented. The other paragraphs are indented to mark the beginning of a paragraph. This is not necessary on the first paragraph after a section heading since it's clear that the text starts there.

Some resources:
https://www.louiseharnbyproofreader.com/blog/when-to-indent-text-laying-out-narrative-and-dialogue-in-fiction
https://tex.stackexchange.com/a/101644/305936
https://www.grammarly.com/blog/great-indentation-debate/

2023-11-28 09:17 UTC, Danar435 commented on src/main.tex
> -\usepackage[indent=20pt]{parskip}
Vi har lige diskuteret det, og vi blev enige om, at det ser bedre ud uden indrykning, fordi der allerede er plads mellem afsnittene på grund af den pakke, vi bruger. Vi vil også spørge, hvad Reza synes. Kan du acceptere det så jeg kan merge?

2023-11-28 13:24 UTC, audio-engineer commented on src/main.tex
> -\usepackage[indent=20pt]{parskip}
Why would you want to _not do_ something, when the norm is exactly _to do_ it? Here are some examples from some of the literature that we are confronted with every day:
<img width="1088" alt="image" src="https://github.com/audio-engineer/aau-p1-article/assets/70742985/1dc8d2a8-fff7-43df-9c4d-24a807dbe367">
<img width="1132" alt="image" src="https://github.com/audio-engineer/aau-p1-article/assets/70742985/bd32f236-dc9e-4909-877f-18c478e69d4d">
<img width="483" alt="image" src="https://github.com/audio-engineer/aau-p1-article/assets/70742985/d61c8d50-08ef-4882-a8e6-45d051a911da">
<img width="537" alt="image" src="https://github.com/audio-engineer/aau-p1-article/assets/70742985/4a6e0a20-2bd9-4388-8af5-f3284f5bff8a">

2023-11-28 13:26 UTC, audio-engineer commented on src/main.tex
> -\usepackage[indent=20pt]{parskip}
More examples:
<img width="698" alt="image" src="https://github.com/audio-engineer/aau-p1-article/assets/70742985/04d5f7fd-a17f-4045-81a6-92d3f140f619">
<img width="698" alt="image" src="https://github.com/audio-engineer/aau-p1-article/assets/70742985/a43b271a-ed8e-4583-b306-07415c2ce07b">

2023-11-29 08:35 UTC, audio-engineer approved these changes

2023-11-29 08:36 UTC, merged