Finish calculations (minus comfort, which is optional)
audio-engineer/aau-p1-article pull request #51
Opened 2023-12-08 09:06 UTC by Danar435

2023-12-09 17:20 UTC, audio-engineer requested changes

2023-12-09 17:20 UTC, audio-engineer commented on src/whitelist.txt
> +Haversine
@Danar435 Can you `rebase` and accept everything from `main` first, then add this line at the bottom?

2023-12-09 17:20 UTC, audio-engineer commented on src/problem-solution/calculations.tex
> +Where $\phi$ is the latitude, $\lambda$ is the longitude, $d$ is the distance and $r$ is the radius of the Earth,
@Danar435 Better use `\(...\)` instead of `$...$` as the rest of the project does.

2023-12-09 17:43 UTC, audio-engineer approved these changes

2023-12-10 13:11 UTC, MadsHeilmann approved these changes

2023-12-10 17:04 UTC, merged